// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPomodoro_API.Context;

#nullable disable

namespace WorkPomodoro_API.Migrations
{
    [DbContext(typeof(WorkPomodoroDbContext))]
    [Migration("20230802075827_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkPomodoro_API.Entity.Account", b =>
                {
                    b.Property<string>("uid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("role")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("status")
                        .HasColumnType("bit");

                    b.Property<string>("username")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("uid");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entity.Song", b =>
                {
                    b.Property<string>("sid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("status")
                        .HasColumnType("int");

                    b.Property<string>("uid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("sid");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entity.Task", b =>
                {
                    b.Property<string>("tid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("accountuid")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("type")
                        .HasColumnType("int");

                    b.Property<string>("uid")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tid");

                    b.HasIndex("accountuid");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entity.Task", b =>
                {
                    b.HasOne("WorkPomodoro_API.Entity.Account", "account")
                        .WithMany("tasks")
                        .HasForeignKey("accountuid");

                    b.Navigation("account");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entity.Account", b =>
                {
                    b.Navigation("tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
