// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WorkPomodoro_API.Entities;

#nullable disable

namespace WorkPomodoro_API.Migrations
{
    [DbContext(typeof(WorkPomodoroContext))]
    partial class WorkPomodoroContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WorkPomodoro_API.Entities.Account", b =>
                {
                    b.Property<int>("Uid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("uid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Uid"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("image")
                        .HasDefaultValueSql("(0x)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("name");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(60)
                        .IsUnicode(false)
                        .HasColumnType("char(60)")
                        .HasColumnName("password")
                        .IsFixedLength();

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(2)
                        .IsUnicode(false)
                        .HasColumnType("char(2)")
                        .HasColumnName("role")
                        .IsFixedLength();

                    b.Property<bool?>("Status")
                        .HasColumnType("bit")
                        .HasColumnName("status");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasColumnName("username");

                    b.HasKey("Uid")
                        .HasName("PK__accounts__DD701264A3FCF6EB");

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("WorkPomodoro_API.Entities.Song", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AccountUid")
                        .IsRequired()
                        .HasColumnType("int")
                        .HasColumnName("accountUid");

                    b.Property<byte[]>("AudioBase64")
                        .IsRequired()
                        .HasColumnType("varbinary(max)")
                        .HasColumnName("audioBase64");

                    b.Property<string>("Duration")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("duration");

                    b.Property<bool>("IsInPlaylist")
                        .HasColumnType("bit");

                    b.Property<string>("Thumbnail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("thumbnail");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("url");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "AccountUid" }, "IX_Songs_accountUid");

                    b.ToTable("Songs");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entities.Task", b =>
                {
                    b.Property<int>("Tid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("tid");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Tid"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<bool?>("Type")
                        .HasColumnType("bit")
                        .HasColumnName("type");

                    b.Property<int?>("Uid")
                        .HasColumnType("int")
                        .HasColumnName("uid");

                    b.HasKey("Tid")
                        .HasName("PK__tasks__DC105B0FD8ECF246");

                    b.HasIndex("Uid");

                    b.ToTable("tasks", (string)null);
                });

            modelBuilder.Entity("WorkPomodoro_API.Entities.Song", b =>
                {
                    b.HasOne("WorkPomodoro_API.Entities.Account", "Account")
                        .WithMany("Songs")
                        .HasForeignKey("AccountUid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entities.Task", b =>
                {
                    b.HasOne("WorkPomodoro_API.Entities.Account", "Account")
                        .WithMany("Tasks")
                        .HasForeignKey("Uid")
                        .HasConstraintName("FK__tasks__uid__17036CC0");

                    b.Navigation("Account");
                });

            modelBuilder.Entity("WorkPomodoro_API.Entities.Account", b =>
                {
                    b.Navigation("Songs");

                    b.Navigation("Tasks");
                });
#pragma warning restore 612, 618
        }
    }
}
