version: '3.4'

networks:
    wp_network:   

services:
  workpomodoroSql:
    container_name: wp_sql_container
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
    - 8002:1433
    environment:
    - ACCEPT_EULA=Y
    - MSSQL_SA_PASSWORD=Vietanhdeptrai0603!

  workpomodoroApi:
    container_name: wp_api_container
    image: ${DOCKER_REGISTRY-}workpomodoroapi
    build:
      context: .
      dockerfile: WorkPomodoro_API/Dockerfile
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - DB_CONNECTION_STRING=Server=workpomodoroSql;Database=WorkPomodoro;User=sa;Password=Vietanhdeptrai0603!;TrustServerCertificate=true 
    ports:
    - 7262:80
    - 7263:443
    depends_on:
    - workpomodoroSql

